
"""cohere_classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q87b6TFwDUd7_pM83mLeLZLTbIBzonbj
"""



import cohere
import os
from cohere.responses.classify import Example
co = cohere.Client('cOL5L8qHbfPK78SVMkOiKkU8tkZntE6UJL1d7jnk') # This is your trial API key

txt_file1 = 'modifiedtxt1.txt'
examples = []
with open(txt_file1, 'r') as file:
  for line in file:
        parts = line.strip().split(',')
        if len(parts) == 2:
            examples.append(Example(parts[0], parts[1]))
inputs=["circular economy is not always good for the customers"]
response = co.classify(
  model='embed-english-v3.0',
  inputs=inputs,
  examples=examples)
print('The confidence levels of the labels are: {}'.format(response.classifications))
